// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OnboardCheck(arg1) {
  return window['go']['main']['App']['OnboardCheck'](arg1);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SpawnDemo() {
  return window['go']['main']['App']['SpawnDemo']();
}
