// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {main} from '../models';
import {diagnose} from '../models';
import {wailsbus} from '../models';
import {issueview} from '../models';
import {llm} from '../models';
import {retry} from '../models';
import {githubauth} from '../models';
import {github} from '../models';
import {workspace} from '../models';
import {store} from '../models';
import {workerpool} from '../models';
import {logbuffer} from '../models';

export function AcknowledgeComment(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ActivateGoal(arg1:string):Promise<void>;

export function AddIssueDep(arg1:string,arg2:number,arg3:types.IssueDep):Promise<void>;

export function AddJiraWorkspace(arg1:main.JiraWorkspaceForm):Promise<void>;

export function AddManualIssue(arg1:string,arg2:number,arg3:string,arg4:string,arg5:Array<string>,arg6:string):Promise<types.Issue>;

export function AddWorkspace(arg1:types.Workspace):Promise<void>;

export function AddWorkspaceToCollection(arg1:string,arg2:string):Promise<void>;

export function ApprovePlan(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ArchiveDone(arg1:string):Promise<number>;

export function AttachManualPR(arg1:string,arg2:number,arg3:string):Promise<void>;

export function CancelRetries(arg1:string,arg2:number):Promise<boolean>;

export function CancelSession(arg1:string):Promise<void>;

export function ClearIssueFailure(arg1:string,arg2:number):Promise<void>;

export function ContinueWork(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ConvertWorkspaceToLocal(arg1:string,arg2:string):Promise<void>;

export function CreateCollection(arg1:string):Promise<types.Collection>;

export function CreateLabel(arg1:string,arg2:types.Label):Promise<types.Label>;

export function CreatePool(arg1:types.Pool):Promise<void>;

export function CreateRemoteWorkspace(arg1:main.RemoteWorkspaceForm):Promise<main.RemoteDeployResult>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteGoal(arg1:string):Promise<void>;

export function DeleteLabel(arg1:string,arg2:string):Promise<void>;

export function DeletePool(arg1:string):Promise<void>;

export function DeleteProviderEntity(arg1:string):Promise<void>;

export function DeployRemoteWorker(arg1:string,arg2:string,arg3:string):Promise<main.RemoteDeployResult>;

export function DiagnoseIssue(arg1:string,arg2:number):Promise<diagnose.IssueDiagnosis>;

export function DiscoverWorkspaceSkills(arg1:string):Promise<Array<types.SkillRef>>;

export function EstimateSpawnCost(arg1:string,arg2:number,arg3:string):Promise<main.SpawnEstimate>;

export function ExportSessionLedgerCSV(arg1:string,arg2:number):Promise<void>;

export function FetchIssueDetail(arg1:string,arg2:number):Promise<types.Issue>;

export function FetchPRChecks(arg1:string,arg2:number):Promise<string>;

export function FilterIssuesByActiveGoal(arg1:Array<types.Issue>):Promise<Array<types.Issue>>;

export function GCWorktrees(arg1:string):Promise<number>;

export function GetAutoPullPaused():Promise<boolean>;

export function GetEventBusDebugEmits():Promise<Array<wailsbus.EmitRecord>>;

export function GetGlobalCostProjection():Promise<main.PoolCostProjection>;

export function GetIssueView(arg1:string,arg2:number):Promise<issueview.IssueView>;

export function GetLabelFilter(arg1:string):Promise<main.LabelFilterState>;

export function GetMidRunQuestion(arg1:string,arg2:number,arg3:string):Promise<types.Question>;

export function GetModelHint(arg1:string,arg2:string):Promise<llm.ModelHint>;

export function GetNotifyPrefs():Promise<main.NotifyPrefs>;

export function GetPollInterval():Promise<number>;

export function GetPoolCostProjection(arg1:string):Promise<main.PoolCostProjection>;

export function GetPoolUsage():Promise<Array<types.PoolUsage>>;

export function GetRepoDefaultBranch(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetRetryQueue(arg1:string):Promise<Array<retry.PendingRetry>>;

export function GetSessionLedger(arg1:string,arg2:number):Promise<Array<types.SessionLedgerRow>>;

export function GetWorkspaceCostProjection(arg1:string):Promise<Array<main.PoolCostProjection>>;

export function GitHubAuthStatus():Promise<githubauth.User>;

export function GitHubListRepos():Promise<Array<github.Repository>>;

export function GitHubLoginPoll():Promise<githubauth.User>;

export function GitHubLoginStart():Promise<githubauth.DeviceCode>;

export function GitHubLogout():Promise<void>;

export function GoalSpendToday(arg1:string):Promise<main.GoalSpendResult>;

export function InspectRepo(arg1:string):Promise<workspace.Inspection>;

export function IsKeyringAvailable():Promise<boolean>;

export function IssueCost(arg1:string,arg2:number):Promise<number>;

export function KillAgentSession(arg1:string):Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function LatestPlan(arg1:string,arg2:number):Promise<types.Plan>;

export function ListArchivedIssues(arg1:string):Promise<Array<types.Issue>>;

export function ListAvailableAgents():Promise<Array<types.AgentInfo>>;

export function ListAvailableSkills(arg1:string):Promise<Array<types.SkillRef>>;

export function ListBundledSkills():Promise<Array<main.BundledSkill>>;

export function ListCollections():Promise<Array<types.Collection>>;

export function ListGoals():Promise<Array<types.Goal>>;

export function ListIssueViews(arg1:string):Promise<Array<issueview.IssueView>>;

export function ListIssues(arg1:string):Promise<Array<types.Issue>>;

export function ListLabels(arg1:string):Promise<Array<types.Label>>;

export function ListMidRunQuestionsLog(arg1:string,arg2:number):Promise<Array<main.QuestionLogEntry>>;

export function ListPRComments(arg1:string,arg2:number):Promise<Array<types.PRComment>>;

export function ListPendingPlans():Promise<Array<store.PendingPlan>>;

export function ListPlans(arg1:string,arg2:number):Promise<Array<types.Plan>>;

export function ListPools():Promise<Array<workerpool.PoolStatus>>;

export function ListProviderEntities():Promise<Array<types.ProviderEntity>>;

export function ListProviders():Promise<Array<main.ProviderInfo>>;

export function ListSessions():Promise<Array<types.Session>>;

export function ListWorkspaces():Promise<Array<types.Workspace>>;

export function MoveIssueColumn(arg1:string,arg2:number,arg3:string):Promise<void>;

export function OnboardCheck(arg1:string):Promise<Array<workspace.OnboardCheck>>;

export function OpenBundledSkill(arg1:string):Promise<void>;

export function OpenOrphanPR(arg1:string,arg2:number):Promise<void>;

export function PickRepoPath():Promise<string>;

export function PlanCostEstimate(arg1:string,arg2:number):Promise<main.CostEstimate>;

export function PoolSpendThisWeek(arg1:string):Promise<number>;

export function PoolSpendToday(arg1:string):Promise<number>;

export function PostPRComment(arg1:string,arg2:number,arg3:string,arg4:boolean):Promise<void>;

export function PrepareManualPushCommand(arg1:string,arg2:number):Promise<string>;

export function ProbeProviderModels(arg1:types.Provider,arg2:string,arg3:string):Promise<Array<string>>;

export function ReadTranscript(arg1:string):Promise<string>;

export function RecentLogs():Promise<Array<logbuffer.Entry>>;

export function RecoverOrphanQuestion(arg1:string,arg2:number):Promise<void>;

export function RefreshIssuesNow():Promise<void>;

export function RejectPlan(arg1:string,arg2:number):Promise<void>;

export function RemoveIssue(arg1:string,arg2:number):Promise<void>;

export function RemoveIssueDep(arg1:string,arg2:number,arg3:types.IssueDep):Promise<void>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function RemoveWorkspaceFromCollection(arg1:string,arg2:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function ReorderIssues(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;

export function ReplaceCFToken(arg1:string,arg2:string):Promise<void>;

export function Replan(arg1:string,arg2:number):Promise<void>;

export function ReplanForce(arg1:string,arg2:number):Promise<void>;

export function ReplayEventBusEmit(arg1:string):Promise<void>;

export function RequestFixForComments(arg1:string,arg2:number,arg3:Array<number>):Promise<void>;

export function ResetPoolCounters():Promise<number>;

export function ResizeAgentTerm(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveConflicts(arg1:string,arg2:number):Promise<void>;

export function RetryExecuteForApprovedPlan(arg1:string,arg2:number):Promise<void>;

export function RetryNow(arg1:string,arg2:number):Promise<boolean>;

export function RotateRemoteWorkerKey(arg1:string,arg2:string):Promise<void>;

export function RunAutoArchiveNow(arg1:string):Promise<number>;

export function RunOrchestrator():Promise<void>;

export function SaveGoal(arg1:types.Goal):Promise<void>;

export function SavePool(arg1:types.Pool):Promise<void>;

export function SaveProviderEntity(arg1:types.ProviderEntity):Promise<void>;

export function SaveWorkspacePipeline(arg1:string,arg2:types.WorkspacePipeline):Promise<void>;

export function SelfHeal(arg1:string,arg2:number):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function SetAutoPullPaused(arg1:boolean):Promise<void>;

export function SetGoalStatus(arg1:string,arg2:string):Promise<void>;

export function SetIssueLabels(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function SetLabelFilter(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function SetNotifyPrefs(arg1:main.NotifyPrefs):Promise<void>;

export function SetPollInterval(arg1:number):Promise<void>;

export function SpawnPlanForIssue(arg1:string,arg2:number):Promise<types.Session>;

export function StartAgentSession(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:number):Promise<types.AgentTermSession>;

export function StoreCFTokenFileFallback(arg1:string,arg2:string):Promise<void>;

export function SubmitAnswers(arg1:main.AnswerSubmission):Promise<void>;

export function SubmitMidRunAnswer(arg1:string,arg2:number,arg3:types.MidRunAnswer):Promise<void>;

export function TestCloudflareToken(arg1:string):Promise<main.CFTokenResult>;

export function TestGitHubPAT(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestJiraConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UnarchiveAll(arg1:string):Promise<void>;

export function UnarchiveIssue(arg1:string,arg2:number):Promise<void>;

export function UpdateCollectionContext(arg1:string,arg2:string):Promise<void>;

export function UpdateLabel(arg1:string,arg2:string,arg3:types.Label):Promise<types.Label>;

export function UpdateWorkspace(arg1:types.Workspace):Promise<void>;

export function ValidatePipeline(arg1:types.WorkspacePipeline):Promise<void>;

export function WorkspaceSpendToday(arg1:string):Promise<number>;

export function WriteAgentInput(arg1:string,arg2:string):Promise<void>;

export function WriteAnswersOnly(arg1:main.AnswerSubmission):Promise<void>;
