// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateGoal(arg1) {
  return window['go']['main']['App']['ActivateGoal'](arg1);
}

export function AddManualIssue(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddManualIssue'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddWorkspace(arg1) {
  return window['go']['main']['App']['AddWorkspace'](arg1);
}

export function ApprovePlan(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApprovePlan'](arg1, arg2, arg3);
}

export function ArchiveDone(arg1) {
  return window['go']['main']['App']['ArchiveDone'](arg1);
}

export function AttachManualPR(arg1, arg2, arg3) {
  return window['go']['main']['App']['AttachManualPR'](arg1, arg2, arg3);
}

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function ClearIssueFailure(arg1, arg2) {
  return window['go']['main']['App']['ClearIssueFailure'](arg1, arg2);
}

export function ContinueWork(arg1, arg2, arg3) {
  return window['go']['main']['App']['ContinueWork'](arg1, arg2, arg3);
}

export function CreateLabel(arg1, arg2) {
  return window['go']['main']['App']['CreateLabel'](arg1, arg2);
}

export function DeleteGoal(arg1) {
  return window['go']['main']['App']['DeleteGoal'](arg1);
}

export function DeleteLabel(arg1, arg2) {
  return window['go']['main']['App']['DeleteLabel'](arg1, arg2);
}

export function DeletePool(arg1) {
  return window['go']['main']['App']['DeletePool'](arg1);
}

export function DiagnoseIssue(arg1, arg2) {
  return window['go']['main']['App']['DiagnoseIssue'](arg1, arg2);
}

export function DiscoverWorkspaceSkills(arg1) {
  return window['go']['main']['App']['DiscoverWorkspaceSkills'](arg1);
}

export function EstimateSpawnCost(arg1, arg2, arg3) {
  return window['go']['main']['App']['EstimateSpawnCost'](arg1, arg2, arg3);
}

export function FetchIssueDetail(arg1, arg2) {
  return window['go']['main']['App']['FetchIssueDetail'](arg1, arg2);
}

export function FetchPRChecks(arg1, arg2) {
  return window['go']['main']['App']['FetchPRChecks'](arg1, arg2);
}

export function FilterIssuesByActiveGoal(arg1) {
  return window['go']['main']['App']['FilterIssuesByActiveGoal'](arg1);
}

export function GCWorktrees(arg1) {
  return window['go']['main']['App']['GCWorktrees'](arg1);
}

export function GetAutoPullPaused() {
  return window['go']['main']['App']['GetAutoPullPaused']();
}

export function GetIssueView(arg1, arg2) {
  return window['go']['main']['App']['GetIssueView'](arg1, arg2);
}

export function GetLabelFilter(arg1) {
  return window['go']['main']['App']['GetLabelFilter'](arg1);
}

export function GetMidRunQuestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMidRunQuestion'](arg1, arg2, arg3);
}

export function GetNotifyPrefs() {
  return window['go']['main']['App']['GetNotifyPrefs']();
}

export function GetPollInterval() {
  return window['go']['main']['App']['GetPollInterval']();
}

export function GetPoolUsage() {
  return window['go']['main']['App']['GetPoolUsage']();
}

export function GitHubAuthStatus() {
  return window['go']['main']['App']['GitHubAuthStatus']();
}

export function GitHubListRepos() {
  return window['go']['main']['App']['GitHubListRepos']();
}

export function GitHubLoginPoll() {
  return window['go']['main']['App']['GitHubLoginPoll']();
}

export function GitHubLoginStart() {
  return window['go']['main']['App']['GitHubLoginStart']();
}

export function GitHubLogout() {
  return window['go']['main']['App']['GitHubLogout']();
}

export function GoalSpendToday(arg1) {
  return window['go']['main']['App']['GoalSpendToday'](arg1);
}

export function InspectRepo(arg1) {
  return window['go']['main']['App']['InspectRepo'](arg1);
}

export function IssueCost(arg1, arg2) {
  return window['go']['main']['App']['IssueCost'](arg1, arg2);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function LatestPlan(arg1, arg2) {
  return window['go']['main']['App']['LatestPlan'](arg1, arg2);
}

export function ListArchivedIssues(arg1) {
  return window['go']['main']['App']['ListArchivedIssues'](arg1);
}

export function ListAvailableSkills(arg1) {
  return window['go']['main']['App']['ListAvailableSkills'](arg1);
}

export function ListBundledSkills() {
  return window['go']['main']['App']['ListBundledSkills']();
}

export function ListGoals() {
  return window['go']['main']['App']['ListGoals']();
}

export function ListIssueViews(arg1) {
  return window['go']['main']['App']['ListIssueViews'](arg1);
}

export function ListIssues(arg1) {
  return window['go']['main']['App']['ListIssues'](arg1);
}

export function ListLabels(arg1) {
  return window['go']['main']['App']['ListLabels'](arg1);
}

export function ListPendingPlans() {
  return window['go']['main']['App']['ListPendingPlans']();
}

export function ListPlans(arg1, arg2) {
  return window['go']['main']['App']['ListPlans'](arg1, arg2);
}

export function ListPools() {
  return window['go']['main']['App']['ListPools']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function MoveIssueColumn(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveIssueColumn'](arg1, arg2, arg3);
}

export function OnboardCheck(arg1) {
  return window['go']['main']['App']['OnboardCheck'](arg1);
}

export function OpenBundledSkill(arg1) {
  return window['go']['main']['App']['OpenBundledSkill'](arg1);
}

export function PickRepoPath() {
  return window['go']['main']['App']['PickRepoPath']();
}

export function PlanCostEstimate(arg1, arg2) {
  return window['go']['main']['App']['PlanCostEstimate'](arg1, arg2);
}

export function PoolSpendThisWeek(arg1) {
  return window['go']['main']['App']['PoolSpendThisWeek'](arg1);
}

export function PoolSpendToday(arg1) {
  return window['go']['main']['App']['PoolSpendToday'](arg1);
}

export function ProbeProviderModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProbeProviderModels'](arg1, arg2, arg3);
}

export function ReadTranscript(arg1) {
  return window['go']['main']['App']['ReadTranscript'](arg1);
}

export function RecentLogs() {
  return window['go']['main']['App']['RecentLogs']();
}

export function RecoverOrphanQuestion(arg1, arg2) {
  return window['go']['main']['App']['RecoverOrphanQuestion'](arg1, arg2);
}

export function RefreshIssuesNow() {
  return window['go']['main']['App']['RefreshIssuesNow']();
}

export function RejectPlan(arg1, arg2) {
  return window['go']['main']['App']['RejectPlan'](arg1, arg2);
}

export function RemoveIssue(arg1, arg2) {
  return window['go']['main']['App']['RemoveIssue'](arg1, arg2);
}

export function RemoveWorkspace(arg1) {
  return window['go']['main']['App']['RemoveWorkspace'](arg1);
}

export function ReorderIssues(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderIssues'](arg1, arg2, arg3);
}

export function Replan(arg1, arg2) {
  return window['go']['main']['App']['Replan'](arg1, arg2);
}

export function ReplanForce(arg1, arg2) {
  return window['go']['main']['App']['ReplanForce'](arg1, arg2);
}

export function ResetPoolCounters() {
  return window['go']['main']['App']['ResetPoolCounters']();
}

export function ResolveConflicts(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflicts'](arg1, arg2);
}

export function RunAutoArchiveNow(arg1) {
  return window['go']['main']['App']['RunAutoArchiveNow'](arg1);
}

export function RunOrchestrator() {
  return window['go']['main']['App']['RunOrchestrator']();
}

export function SaveGoal(arg1) {
  return window['go']['main']['App']['SaveGoal'](arg1);
}

export function SavePool(arg1) {
  return window['go']['main']['App']['SavePool'](arg1);
}

export function SaveWorkspacePipeline(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkspacePipeline'](arg1, arg2);
}

export function SelfHeal(arg1, arg2) {
  return window['go']['main']['App']['SelfHeal'](arg1, arg2);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SetAutoPullPaused(arg1) {
  return window['go']['main']['App']['SetAutoPullPaused'](arg1);
}

export function SetGoalStatus(arg1, arg2) {
  return window['go']['main']['App']['SetGoalStatus'](arg1, arg2);
}

export function SetIssueLabels(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIssueLabels'](arg1, arg2, arg3);
}

export function SetLabelFilter(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLabelFilter'](arg1, arg2, arg3);
}

export function SetNotifyPrefs(arg1) {
  return window['go']['main']['App']['SetNotifyPrefs'](arg1);
}

export function SetPollInterval(arg1) {
  return window['go']['main']['App']['SetPollInterval'](arg1);
}

export function SpawnDemo() {
  return window['go']['main']['App']['SpawnDemo']();
}

export function SpawnPlanForIssue(arg1, arg2) {
  return window['go']['main']['App']['SpawnPlanForIssue'](arg1, arg2);
}

export function SubmitAnswers(arg1) {
  return window['go']['main']['App']['SubmitAnswers'](arg1);
}

export function SubmitMidRunAnswer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitMidRunAnswer'](arg1, arg2, arg3);
}

export function UnarchiveAll(arg1) {
  return window['go']['main']['App']['UnarchiveAll'](arg1);
}

export function UnarchiveIssue(arg1, arg2) {
  return window['go']['main']['App']['UnarchiveIssue'](arg1, arg2);
}

export function UpdateLabel(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateLabel'](arg1, arg2, arg3);
}

export function UpdateWorkspace(arg1) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1);
}

export function ValidatePipeline(arg1) {
  return window['go']['main']['App']['ValidatePipeline'](arg1);
}

export function WorkspaceSpendToday(arg1) {
  return window['go']['main']['App']['WorkspaceSpendToday'](arg1);
}

export function WriteAnswersOnly(arg1) {
  return window['go']['main']['App']['WriteAnswersOnly'](arg1);
}
