// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {main} from '../models';
import {githubauth} from '../models';
import {github} from '../models';
import {workspace} from '../models';

export function ActivateGoal(arg1:string):Promise<void>;

export function AddManualIssue(arg1:string,arg2:number,arg3:string,arg4:string,arg5:Array<string>,arg6:string):Promise<types.Issue>;

export function AddWorkspace(arg1:types.Workspace):Promise<void>;

export function DeleteGoal(arg1:string):Promise<void>;

export function FilterIssuesByActiveGoal(arg1:Array<types.Issue>):Promise<Array<types.Issue>>;

export function GetOllamaConfig():Promise<main.OllamaConfig>;

export function GitHubAuthStatus():Promise<githubauth.User>;

export function GitHubListRepos():Promise<Array<github.Repository>>;

export function GitHubLoginPoll():Promise<githubauth.User>;

export function GitHubLoginStart():Promise<githubauth.DeviceCode>;

export function GitHubLogout():Promise<void>;

export function InspectRepo(arg1:string):Promise<workspace.Inspection>;

export function KillSession(arg1:string):Promise<void>;

export function ListGoals():Promise<Array<types.Goal>>;

export function ListIssues(arg1:string):Promise<Array<types.Issue>>;

export function ListSessions():Promise<Array<types.Session>>;

export function ListWorkspaces():Promise<Array<types.Workspace>>;

export function MoveIssueColumn(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OnboardCheck(arg1:string):Promise<Array<workspace.OnboardCheck>>;

export function PickRepoPath():Promise<string>;

export function ReadTranscript(arg1:string):Promise<string>;

export function RemoveIssue(arg1:string,arg2:number):Promise<void>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function ReorderIssues(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;

export function RunOrchestrator():Promise<void>;

export function SaveGoal(arg1:types.Goal):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function SetGoalStatus(arg1:string,arg2:string):Promise<void>;

export function SetOllamaConfig(arg1:main.OllamaConfig):Promise<void>;

export function SpawnDemo():Promise<types.Session>;

export function SpawnPlanForIssue(arg1:string,arg2:number):Promise<types.Session>;

export function UpdateWorkspace(arg1:types.Workspace):Promise<void>;
