// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateGoal(arg1) {
  return window['go']['main']['App']['ActivateGoal'](arg1);
}

export function AddWorkspace(arg1) {
  return window['go']['main']['App']['AddWorkspace'](arg1);
}

export function DeleteGoal(arg1) {
  return window['go']['main']['App']['DeleteGoal'](arg1);
}

export function GitHubAuthStatus() {
  return window['go']['main']['App']['GitHubAuthStatus']();
}

export function GitHubListRepos() {
  return window['go']['main']['App']['GitHubListRepos']();
}

export function GitHubLoginPoll() {
  return window['go']['main']['App']['GitHubLoginPoll']();
}

export function GitHubLoginStart() {
  return window['go']['main']['App']['GitHubLoginStart']();
}

export function GitHubLogout() {
  return window['go']['main']['App']['GitHubLogout']();
}

export function InspectRepo(arg1) {
  return window['go']['main']['App']['InspectRepo'](arg1);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function ListGoals() {
  return window['go']['main']['App']['ListGoals']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OnboardCheck(arg1) {
  return window['go']['main']['App']['OnboardCheck'](arg1);
}

export function PickRepoPath() {
  return window['go']['main']['App']['PickRepoPath']();
}

export function ReadTranscript(arg1) {
  return window['go']['main']['App']['ReadTranscript'](arg1);
}

export function RemoveWorkspace(arg1) {
  return window['go']['main']['App']['RemoveWorkspace'](arg1);
}

export function SaveGoal(arg1) {
  return window['go']['main']['App']['SaveGoal'](arg1);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SetGoalStatus(arg1, arg2) {
  return window['go']['main']['App']['SetGoalStatus'](arg1, arg2);
}

export function SpawnDemo() {
  return window['go']['main']['App']['SpawnDemo']();
}

export function SpawnPlanForIssue(arg1, arg2) {
  return window['go']['main']['App']['SpawnPlanForIssue'](arg1, arg2);
}

export function UpdateWorkspace(arg1) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1);
}
